import pandas as pd
import numpy as np

print("Loading daily indicators and live CMP...")

try:
    # Load the daily EOD data (generated after market close)
    daily_df = pd.read_csv('daily_rs_data.csv')
    
    # Load the live CMP data (generated by your GitHub Action)
    live_df = pd.read_csv('live_cmp.csv')
except FileNotFoundError as e:
    print(f"Error loading files: {e}")
    exit()

# Merge the datasets on Symbol
df = pd.merge(live_df, daily_df, on='Symbol', how='inner')

# ==========================================
# 1. LIVE RETURN CALCULATION (T, T-1, T-2 Fallback)
# ==========================================
# Let P_t   = Today's live price (CMP)
# Let P_t_1 = Yesterday's closing price (Prev_Close)
P_t = df['CMP']
P_t_1 = df['Prev_Close']

# Standard Live Return (Decimal format)
live_return = (P_t - P_t_1) / P_t_1

# FALLBACK LOGIC: If T == T-1 (Market is closed/hasn't opened), use T-2's return.
# Note: The daily file stores '1D Return %' as a percentage (e.g., 2.5), 
# so we divide by 100 to match our decimal logic (0.025).
df['Live_1D_Return'] = np.where(
    P_t == P_t_1, 
    df['1D Return %'] / 100, 
    live_return
)

# ==========================================
# 2. STRATEGY PARAMETERS
# ==========================================
is_index_down = df['Index_ST_DIR'] == 'Down'

rsi_threshold = 55
return_1d_threshold = -0.05
rs_score_threshold = np.where(is_index_down, 95, 80)

# ==========================================
# 3. APPLY STOCK SELECTION & BUY RULES
# ==========================================
stock_selection = (
    (df['RSI_14'] >= rsi_threshold) &
    (df['Live_1D_Return'] > return_1d_threshold) &
    ((df['3M_Return'] > 0.20) | (df['6M_Return'] > 0.30) | (df['1M_Return'] > 0.10)) &
    (df['SMA_50'] > df['SMA_200'])
)

buy_condition = (
    (df['RS_Score'] > rs_score_threshold) &
    (df['CMP'] > df['SMA_200']) &
    (df['CMP'] > df['ST_15_3']) &
    (df['CMP'] >= df['EMA_9'] * 0.95) & 
    (df['CMP'] <= df['EMA_9'] * 1.05)
)

# Filter for valid signals
df_signals = df[stock_selection & buy_condition].copy()

print(f"Found {len(df_signals)} stocks meeting all strategy criteria.")

# Select Top 6 based on RS_Score
top_allocations = df_signals.sort_values(by='RS_Score', ascending=False).head(6).copy()

# ==========================================
# 4. POSITION SIZING & EXPORT
# ==========================================
INITIAL_CAPITAL = 100000.0
MAX_POSITIONS = 6
POSITION_SIZE = INITIAL_CAPITAL / MAX_POSITIONS

if not top_allocations.empty:
    # Stoploss: 15% if Index is Down, 13% if Index is Up
    sl_multiplier = np.where(top_allocations['Index_ST_DIR'] == 'Down', 0.85, 0.87)
    
    top_allocations['Target_Entry_Price'] = top_allocations['CMP']
    top_allocations['Stop_Loss'] = (top_allocations['CMP'] * sl_multiplier).round(2)
    
    # Calculate Quantity based on live CMP
    top_allocations['Quantity'] = (POSITION_SIZE // top_allocations['CMP']).astype(int)
    
    # Calculate EXACT Investment Percentage for the Donut Chart
    actual_invested_value = top_allocations['Quantity'] * top_allocations['CMP']
    top_allocations['Investment_Percentage'] = ((actual_invested_value / INITIAL_CAPITAL) * 100).round(2)
    
    # Format output (Live_1D_Return is rounded for cleaner viewing in PowerBI)
    top_allocations['Live_1D_Return'] = top_allocations['Live_1D_Return'].round(4)
    
    final_cols = ['Symbol', 'CMP', 'Live_1D_Return', 'RS_Score', 'Quantity', 'Target_Entry_Price', 'Stop_Loss', 'Investment_Percentage', 'Index_ST_DIR']
    output_df = top_allocations[final_cols]
    
    output_df.to_csv('target_allocations.csv', index=False)
    print(f"Successfully exported {len(output_df)} allocations to target_allocations.csv")
else:
    # Create empty CSV with matching headers so PowerBI refresh doesn't fail
    pd.DataFrame(columns=['Symbol', 'CMP', 'Live_1D_Return', 'RS_Score', 'Quantity', 'Target_Entry_Price', 'Stop_Loss', 'Investment_Percentage', 'Index_ST_DIR']).to_csv('target_allocations.csv', index=False)
    print("No valid signals found. Exported empty target_allocations.csv.")
