import pandas as pd
import numpy as np
import pandas_ta as ta
import yfinance as yf
import os
import warnings
from datetime import datetime, timedelta
import pytz

warnings.filterwarnings('ignore')

# --- CONFIGURATION ---
ANGEL_DB_FILE = "historical_db.csv"  # Generated by your daily Angel RS script
HISTORICAL_CSV = "historical_portfolio_value.csv"
ALLOCATIONS_CSV = "daily_allocations.csv"
MAX_POSITIONS = 6
INITIAL_CAPITAL = 100000.0

ist = pytz.timezone('Asia/Kolkata')
now_ist = datetime.now(ist)
start_date_str = (now_ist - timedelta(days=5*365)).strftime('%Y-%m-%d')

print(f"Running EOD Strategy. Time (IST): {now_ist.strftime('%Y-%m-%d %H:%M:%S')}")

# 1. Load Angel Historical Data
if not os.path.exists(ANGEL_DB_FILE):
    print(f"ERROR: {ANGEL_DB_FILE} not found. Ensure your Angel RS fetcher runs before this script.")
    exit()

print(f"Loading Angel data from {ANGEL_DB_FILE}...")
df = pd.read_csv(ANGEL_DB_FILE)

# Standardize columns for the backtest engine
df.rename(columns={
    'Date': 'DATE', 'Symbol': 'TICKER', 'Open': 'OPEN',
    'High': 'HIGH', 'Low': 'LOW', 'Close': 'CLOSE', 'Volume': 'VOLUME'
}, inplace=True)

df['DATE'] = pd.to_datetime(df['DATE']).dt.tz_localize(None)
df.dropna(subset=['CLOSE'], inplace=True)

# Filter for the last 5 years to keep the backtest window standard
cutoff_date = pd.to_datetime(start_date_str)
df = df[df['DATE'] >= cutoff_date]

# 2. Fetch Index Data for Regime Filter (yfinance is best for the broad index)
print("Downloading Nifty 500 Index data for regime filter...")
index_ticker = "^CRSLDX"
index_data = yf.download(index_ticker, start=start_date_str, progress=False, auto_adjust=False)

if index_data.empty:
    index_ticker = "^NSEI"
    index_data = yf.download(index_ticker, start=start_date_str, progress=False, auto_adjust=False)

if isinstance(index_data.columns, pd.MultiIndex):
    index_data.columns = index_data.columns.droplevel(1)

index_data = index_data.reset_index()
index_data.rename(columns={'Date': 'DATE', 'High': 'HIGH', 'Low': 'LOW', 'Close': 'CLOSE'}, inplace=True)
index_data['DATE'] = pd.to_datetime(index_data['DATE']).dt.tz_localize(None)

st_idx = ta.supertrend(high=index_data['HIGH'], low=index_data['LOW'], close=index_data['CLOSE'], length=15, multiplier=2.75)
index_data['Index_ST_DIR'] = st_idx.iloc[:, 1].map({1: 'Up', -1: 'Down'}) if st_idx is not None else 'Up'
index_regime = index_data[['DATE', 'Index_ST_DIR']].dropna()

# 3. Calculate Indicators
print("Calculating Strategy Indicators...")
df = df.sort_values(by=['TICKER', 'DATE']).reset_index(drop=True)

df['1D_Return'] = df.groupby('TICKER')['CLOSE'].pct_change(1)
df['1M_Return'] = df.groupby('TICKER')['CLOSE'].pct_change(21)
df['3M_Return'] = df.groupby('TICKER')['CLOSE'].pct_change(63)
df['6M_Return'] = df.groupby('TICKER')['CLOSE'].pct_change(126)
df['9M_Return'] = df.groupby('TICKER')['CLOSE'].pct_change(189)
df['12M_Return'] = df.groupby('TICKER')['CLOSE'].pct_change(252)

df['SMA_50'] = df.groupby('TICKER')['CLOSE'].transform(lambda x: ta.sma(x, length=50))
df['SMA_200'] = df.groupby('TICKER')['CLOSE'].transform(lambda x: ta.sma(x, length=200))
df['EMA_9'] = df.groupby('TICKER')['CLOSE'].transform(lambda x: ta.ema(x, length=9))
df['RSI_14'] = df.groupby('TICKER')['CLOSE'].transform(lambda x: ta.rsi(x, length=14))

st_list = []
for ticker, group in df.groupby('TICKER'):
    st = ta.supertrend(high=group['HIGH'], low=group['LOW'], close=group['CLOSE'], length=15, multiplier=2.75)
    st_res = pd.DataFrame({'ST_15_3': st.iloc[:, 0], 'ST_DIR': st.iloc[:, 1].map({1: 'Up', -1: 'Down'})} if st is not None else {'ST_15_3': np.nan, 'ST_DIR': np.nan}, index=group.index)
    st_list.append(st_res)

st_df = pd.concat(st_list)
df['ST_15_3'] = st_df['ST_15_3']
df['ST_DIR'] = st_df['ST_DIR']

df['Weighted Avg'] = (0.3 * df['3M_Return'] + 0.3 * df['6M_Return'] + 0.2 * df['9M_Return'] + 0.2 * df['12M_Return'])
df['RS_Score'] = df.groupby('DATE')['Weighted Avg'].rank(pct=True) * 100
df['RS_Score'] = df['RS_Score'].round(0).clip(lower=1, upper=99)

df_bt = df.dropna(subset=['SMA_200', '12M_Return', 'RS_Score', 'ST_15_3']).copy()
df_bt = pd.merge(df_bt, index_regime, on='DATE', how='left')
df_bt['Index_ST_DIR'] = df_bt['Index_ST_DIR'].ffill().fillna('Up')

# 4. Signal Logic
is_not_circuit = df_bt['HIGH'] != df_bt['LOW']
is_index_down = df_bt['Index_ST_DIR'] == 'Down'

rsi_threshold = np.where(is_index_down, 55, 55)
return_1d_threshold = np.where(is_index_down, -0.05, -0.05)
rs_score_threshold = np.where(is_index_down, 95, 80)

stock_selection = ((df_bt['RSI_14'] >= rsi_threshold) & (df_bt['1D_Return'] > return_1d_threshold) & 
                   ((df_bt['3M_Return'] > 0.20) | (df_bt['6M_Return'] > 0.30) | (df_bt['1M_Return'] > 0.10)) & 
                   (df_bt['SMA_50'] > df_bt['SMA_200']))

buy_condition = ((df_bt['RS_Score'] > rs_score_threshold) & (df_bt['CLOSE'] > df_bt['SMA_200']) & 
                 (df_bt['CLOSE'] > df_bt['ST_15_3']) & (df_bt['CLOSE'] >= df_bt['EMA_9'] * 0.95) & 
                 (df_bt['CLOSE'] <= df_bt['EMA_9'] * 1.05))

df_bt['Buy_Signal'] = is_not_circuit & stock_selection & buy_condition

shift_cols = ['Buy_Signal', 'CLOSE', 'ST_15_3', 'SMA_200', 'RS_Score', 'RSI_14', '3M_Return', '6M_Return', '9M_Return', 'ST_DIR', 'Index_ST_DIR']
for col in shift_cols:
    df_bt[f'Prev_{col}'] = df_bt.groupby('TICKER')[col].shift(1)

df_bt['Prev_Buy_Signal'] = df_bt['Prev_Buy_Signal'].fillna(False).astype(bool)

# 5. Backtest Engine
print("Running Backtest Engine...")
capital = INITIAL_CAPITAL
positions = {}
equity_curve = []
unique_dates = sorted(df_bt['DATE'].unique())

POSITION_SIZE = INITIAL_CAPITAL / MAX_POSITIONS
BROKERAGE_RATE = 0.005

for current_date in unique_dates:
    daily_data = df_bt[df_bt['DATE'] == current_date].set_index('TICKER')
    tickers_to_remove = []
    
    # Process Sells
    for ticker, pos in positions.items():
        if ticker in daily_data.index:
            row = daily_data.loc[ticker]
            today_open, today_low, today_high = row['OPEN'], row['LOW'], row['HIGH']
            prev_close, prev_st, prev_sma, prev_index_st = row['Prev_CLOSE'], row['Prev_ST_15_3'], row['Prev_SMA_200'], row['Prev_Index_ST_DIR']
            
            if today_high == today_low: continue

            triggered_sell = False
            if pd.notna(prev_close) and pd.notna(prev_st) and prev_close < prev_st:
                exit_price = today_open
                triggered_sell = True
            elif pd.notna(prev_close) and pd.notna(prev_sma) and prev_close < prev_sma:
                exit_price = today_open
                triggered_sell = True
            
            if not triggered_sell:
                sl_multiplier = 0.85 if prev_index_st == 'Down' else 0.87
                sl_price = pos['raw_entry_price'] * sl_multiplier
                if today_open <= sl_price:
                    exit_price = today_open
                    triggered_sell = True
                elif today_low <= sl_price:
                    exit_price = sl_price
                    triggered_sell = True

            if triggered_sell:
                net_exit_price = exit_price * (1 - BROKERAGE_RATE)
                capital += (net_exit_price * pos['qty'])
                tickers_to_remove.append(ticker)

    for t in tickers_to_remove: del positions[t]

    # Process Buys
    buy_signals = daily_data[daily_data['Prev_Buy_Signal']].sort_values(by='Prev_RS_Score', ascending=False)
    for ticker, row in buy_signals.iterrows():
        if row['HIGH'] == row['LOW']: continue
        if len(positions) < MAX_POSITIONS and ticker not in positions:
            invest_amount = POSITION_SIZE if capital >= POSITION_SIZE else capital
            execution_price = row['OPEN']
            net_buy_price = execution_price * (1 + BROKERAGE_RATE)

            if invest_amount > net_buy_price:
                qty = int(invest_amount // net_buy_price)
                cost = qty * net_buy_price
                positions[ticker] = {
                    'raw_entry_price': execution_price, 'net_entry_price': net_buy_price,
                    'qty': qty, 'entry_date': current_date, 'index_st': row['Prev_Index_ST_DIR']
                }
                capital -= cost

    # Daily Equity
    daily_portfolio_value = capital
    for ticker, pos in positions.items():
        if ticker in daily_data.index:
            daily_portfolio_value += pos['qty'] * daily_data.loc[ticker, 'CLOSE']
        else:
            daily_portfolio_value += pos['qty'] * pos['raw_entry_price']

    equity_curve.append({'Date': current_date, 'Equity': daily_portfolio_value})

# 6. Post-Market Mutation (Prepare targets for tomorrow)
latest_date = unique_dates[-1]
last_day_data = df_bt[df_bt['DATE'] == latest_date].set_index('TICKER')

sells_for_tomorrow = []
for ticker, pos in positions.items():
    if ticker in last_day_data.index:
        row = last_day_data.loc[ticker]
        todays_close, todays_st, todays_sma = row['CLOSE'], row['ST_15_3'], row['SMA_200']
        if pd.notna(todays_close) and ((pd.notna(todays_st) and todays_close < todays_st) or (pd.notna(todays_sma) and todays_close < todays_sma)):
            sells_for_tomorrow.append(ticker)

for t in sells_for_tomorrow: del positions[t]

buy_candidates = last_day_data[last_day_data['Buy_Signal']].sort_values(by='RS_Score', ascending=False)
for ticker, row in buy_candidates.iterrows():
    if len(positions) < MAX_POSITIONS and ticker not in positions:
        positions[ticker] = {
            'raw_entry_price': 'Will update when market opens',
            'qty': 'TBD',
            'entry_date': 'Pending Next Open',
            'index_st': row['Index_ST_DIR']
        }

# 7. EXPORT CSVs
# A. Equity Curve
equity_df = pd.DataFrame(equity_curve)
equity_df['Drawdown'] = equity_df['Equity'] / equity_df['Equity'].cummax() - 1
equity_df['Daily_Return'] = equity_df['Equity'].pct_change()
equity_df.to_csv(HISTORICAL_CSV, index=False)
print(f"Exported {len(equity_df)} days of history to {HISTORICAL_CSV}")

# B. Allocations
alloc_list = []
latest_equity = equity_curve[-1]['Equity'] if equity_curve else INITIAL_CAPITAL

for t, p in positions.items():
    sl_multiplier = 0.85 if p.get('index_st', 'Up') == 'Down' else 0.87
    
    if p['raw_entry_price'] == 'Will update when market opens':
        action = "BUY"
        sl_val = "TBD"
        # Target allocation is an equal split of the portfolio
        alloc_pct = round((1.0 / MAX_POSITIONS) * 100, 2)
    else:
        action = "HOLD"
        sl_val = round(p['raw_entry_price'] * sl_multiplier, 2)
        # Calculate actual active allocation percentage
        alloc_pct = round(((p['qty'] * p['raw_entry_price']) / latest_equity) * 100, 2)
        
    alloc_list.append({
        'Ticker': t,
        'Action': action,
        'Entry_Price': p['raw_entry_price'],
        'Quantity': p['qty'],
        'Stoploss': sl_val,
        'Allocation_%': alloc_pct,
        'Entry_Date': p['entry_date']
    })

alloc_df = pd.DataFrame(alloc_list)
alloc_df.to_csv(ALLOCATIONS_CSV, index=False)
print(f"Exported {len(alloc_df)} targets to {ALLOCATIONS_CSV}")
